### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pberki** [pkejval/uld-docker#1]
I have an istallation problem (on Kubuntu 22.04):

docker build --tag ulozto-downloader .

....
179650K .......... .......... .......... .......... .......... 99% 39.2M 0s
179700K .......... .......... .......... .......... .......... 99% 41.7M 0s
179750K .......... .......... .......... .......... .......... 99% 39.4M 0s
179800K .......... .......... .......... .......... .......... 99% 31.1M 0s
179850K .......... .......... .......... .......... .......... 99% 35.2M 0s
179900K .......... .                                          100%  805M=4.7s

2023-08-21 14:26:39 (37.0 MB/s) - 'flaresolverr_linux_x64.tar.gz' saved [184229601/184229601]

Removing intermediate container b600eb06f354
 ---> d3cc72776c66
Step 10/17 : RUN tar xvzf flaresolverr_linux_x64.tar.gz
 ---> Running in 22f1dee4f9e8
tar (child): flaresolverr_linux_x64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by pkejval** [comment]
I tested it in Windows and Alpine Linux and never happened to me. I'll try Kubuntu in VM and investigate.

**Comment by pkejval** [comment]
@pberki Could you please test now? https://github.com/pkejval/uld-docker/commit/d47915abd0bea94e3ec0ac0d042bdfd917cdf5f1 should solve it. Working for me in Kubuntu 22.04 VM.

**Comment by pberki** [comment]
I found the problem:
I installed the docker by "sudo apt install docker". 
After uninstallation and installation according to the instructions: "https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04" it works.
I have to change the permissions of "run.sh" to 755.

**Comment by pkejval** [comment]
Okay. Thanks for testing it out. 😄
