### ISSUE TITLE
Does not start downloading

### ISSUE THREAD

**Issue by jesusdeveloper** [pkejval/uld-docker#3]
Hello!
It does not work for me. Installed docker, then I run with run and something like this:
`docker run pkejval/uld-docker:main "https://ulozto.net/file/fdJujPdNGG8n/025-nueva-zelanda-la-isla-de-la-gran-nube-blanca-by-rusochinojapones-part1-rar"`
And the answer that comes back to me is:
```
Starting FlareSolverr
Starting ulozto-downloader

/app/run.sh: line 26:     8 Illegal instruction     python3 /app/ulozto-downloader/ulozto-downloader.py --auto-captcha --output "/downloads" "$@"
```
Does anyone have any ideas? 
THANK YOU!
Good job!

**Comment by pkejval** [comment]
Hi, your CPU doesn't have an available function/instruction for tensorflow to work.
This is not ulozto-downloader nor this docker image issue, sorry. :'(

**Comment by pkejval** [comment]
@jesusdeveloper CPU missing AVX or AVX2 needed for Tensorflow to run.

**Comment by jesusdeveloper** [comment]
> @jesusdeveloper CPU missing AVX or AVX2 needed for Tensorflow to run.

Oh, okay! Sorry! Thanks friend for your help! =)

**Comment by moimg40** [comment]
Where is the file saved? I looked and didn't find it.

**Comment by pkejval** [comment]
Which file? What are you talking about?

If you mean downloaded file it is in /downloads in container. If you want to access it you should navigate to docker volumes folder in your computer (/var/lib/docker/volumes in Linux) or bind-mount /downloads to any folder you want in your computer when creating container.

**Comment by moimg40** [comment]
I managed to find it. Thanks.

> Which file? What are you talking about?
> 
> If you mean downloaded file it is in /downloads in container. If you want to access it you should navigate to docker volumes folder in your computer (/var/lib/docker/volumes in Linux) or bind-mount /downloads to any folder you want in your computer when creating container.
