### ISSUE TITLE
[Feature Request] Example docker compose file

### ISSUE THREAD

**Issue by Pheggas** [pkejval/uld-docker#4]
Hey. Do you mind share a basic docker compose yaml file for those who want to deploy it on their home servers?

**Comment by Pheggas** [comment]
Nevermind. It is just short living container as you're using arguments in docker run command. Closing.

**Comment by pkejval** [comment]
Yes it's only oneshot container right now just to contain all needed software to run. Hovewer you can make file "download.txt" with URLS in "/downloads" directory to make it download multiple files.

**Comment by Pheggas** [comment]
Thank you. Great feature!

**Comment by moimg40** [comment]
I'm getting this message: Cloudflare WAF blocked.. get new TOR session.
