### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by SonGokussj4** [pkejval/uld-docker#8]
Working really nice. Thank you :-)
But the README needs to be a little bit improved. Specifically how to set the environment variables, how to start the script and how to bind the downloads folder.
Because the first time I just run the script with URL, the file downloaded but is nowhere to be found in my system.

### Fix:
`Run command docker run pkejval/uld-docker "URL"` should be `Run command docker run pkejval/uld-docker:main "URL"` 
Else it would return "no image found"

### Modify:
You can create file called download.txt in bind mounted folder /downloads and paste URLs to download. Each URL on new line. If uld-docker finds this file at startup it will download every URL from this file.

to

You can create file called download.txt in bind mounted folder /downloads and paste URLs to download. Each URL on new line. If uld-docker finds this file at startup it will download every URL from this file.
```bash
# Example
mkdir C:\uld-docker
mkdir C:\uld-docker\downloads
cd C:\uld-docker

# Create a downloads/download.txt file and add links inside

# Run
docker run pkejval/uld-docker:main -v .\downloads\:downloads
```

Or something like that.
I haven't experimented with the env variables yet, because I'm not sure how exactly. If I can just add
```powershell
Set-Item "env:PARTS" "50"
```
To my $PROFILE file in powershell or I have to specify `docker run --env PARTS=50` on each script run.

Some people don't know docker so well so any help is welcome :-)

P.S. Really good job. I can finally use uld again.

**Comment by pkejval** [comment]
Hello, thanks for appreciating my work but all credits and thanks must go to all contributors of ulozto-downloader, tor, flaresolverr and other projects. I just stitched their work into package.

Also thanks for suggestions. I'm not interested in writing detailed instructions. If you have time and will to do it, I'll gladly accept PR. Thanks.
